apiVersion: backstage.io/v1alpha1
kind: Location

metadata:
  name: paved-road-catalog
  description: Registers Backstage templates, users, systems, and platform entities for the Paved Road Engine

spec:
  type: file
  targets:
    - ./templates/cloud-run/template.yaml
    - ./users.yaml
    - ./entities/system.yaml
    - ./entities/platform-component.yaml